name: Update version after release

on:
  release:
    types: [prereleased]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Update files
        uses: MathieuSoysal/file-updater-for-release@v1.0.3
        with:
          files: VERSION
          with-checkout: false

      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: Github Actions
          committer_email: actions@github.com
          add: .
          message: "Updated version"

